# Generated by Django 6.0.1 on 2026-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0012_allow_reviews_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='ai_summary',
            field=models.TextField(blank=True, null=True, verbose_name='AI 摘要'),
        ),
    ]
